
services:
  app:
    # Вказуємо Docker зібрати цей сервіс з Dockerfile у поточній теці (.)
    build: .
    ports:
      - "3000:3000"
    # Синхронізуємо файли. Зміни в коді на комп'ютері миттєво з'являться в контейнері.
    volumes:
      - .:/app
      - /app/node_modules 
    environment:
      - MONGO_URI=mongodb://mongo:27017/med-analyzer
    depends_on:
      - mongo

  # 2. Сервіс бази даних MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: